services:
  - type: web
    name: sign-up-frontend-project
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: NODE_VERSION
        value: 18
    build:
      publish: dist
